# permissions for end users to edit createsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: createsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secret-operator
    app.kubernetes.io/part-of: secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: createsecret-editor-role
rules:
- apiGroups:
  - customproject.io
  resources:
  - createsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customproject.io
  resources:
  - createsecrets/status
  verbs:
  - get
