apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: secret-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CreateSecret is the Schema for the createsecrets API
      displayName: Create Secret
      kind: CreateSecret
      name: createsecrets.customproject.io
      version: v1
  description: Used to Create Secret
  displayName: create-secret-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cso
  - createsecretoperator
  links:
  - name: Secret Operator
    url: https://secret-operator.domain
  maintainers:
  - email: keyurbarapatre@gmail.com
    name: Keyur
  maturity: alpha
  provider:
    name: customproject
  version: 0.0.0
